package gpt.specialRules;

public enum SpecialRuleType {
    CHARGE_AGILITY_BONUS, DEVASTATING_CHARGE, FIGHT_IN_EXTRA_RANKS, HARNESSED, INANIMATE, LIGHTNING_REFLEXES, MULTIPLE_WOUNDS, SPEAR, AEGIS, SWORD_SWORN, BATTLE_FOCUS
}
